services:
  homelyy-backend:
    build:
      context: ./backend
    container_name: homelyy-backend
    ports:
      - "${BACKEND_PORT:-4000}:4000"
    environment:
      NODE_ENV: production
      PORT: 4000
      CLIENT_URL: http://localhost:${FRONTEND_PORT:-8080}
      MONGODB_URI: ${MONGODB_URI}
      DB_NAME: ${DB_NAME:-homelyy}
      AUTO_SEED: ${AUTO_SEED:-false}
      JWT_SECRET: ${JWT_SECRET:-homelyy-super-secret-key}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}

  homelyy-frontend:
    build:
      context: ./frontend
    container_name: homelyy-frontend
    depends_on:
      - homelyy-backend
    ports:
      - "${FRONTEND_PORT:-8080}:80"
